#5 Consistent 2 space formatting

diff --git a/.githooks/pre-commit b/.githooks/pre-commit
--- a/.githooks/pre-commit
+++ b/.githooks/pre-commit
@@ -10,32 +10,33 @@ FAILURE=false
 STAGED_FILES=$(git ls-files --full-name | grep ".go$")
 
 if [[ "$STAGED_FILES" = "" ]]; then
+  printf "\e[90mDone! \e[0;39m\n"
   exit 0
 fi
 
 # Run go lint on the tracked files
 printf "\e[90mRunning golint...\e[0;39m\n"
 for stagedFile in $STAGED_FILES; do
-    # Run golint
-    $(golint -set_exit_status $stagedFile)
-    if [[ $? != 0 ]]; then
-        FAILURE=true
-    fi
+  # Run golint
+  $(golint -set_exit_status $stagedFile)
+  if [[ $? != 0 ]]; then
+    FAILURE=true
+  fi
 done
 
 # Run go vet on the entire package, doesn't support single files like lint
 printf "\e[90mRunning go vet...\e[0;39m\n"
 go vet $STAGED_FILES
 if [[ $? != 0 ]]; then
-    FAILURE=true
+  FAILURE=true
 fi
 
 # We are done
 printf "\e[90mDone! \e[0;39m\n"
 
 if [[ $FAILURE != false ]]; then
-    printf "\n\e[1;91mCommit Failed! \e[0;39m\n"
-    exit 1
+  printf "\n\e[1;91mCommit Failed! \e[0;39m\n"
+  exit 1
 fi
 printf "\n\e[1;32mCommit Successful! \e[0;39m\n"
 exit 0
